/* =========================================================
   APX BUSINESS WORLD — ĐIỀU HÀNH TẬP ĐOÀN VÀ CÔNG TY
   Số liệu gameplay luôn lấy từ state.companyOperations.
   ========================================================= */
window.APXPages = window.APXPages || {};
(function () {
  "use strict";
  function esc(value) {
    return String(value == null ? "" : value).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; });
  }
  function fmt(value) { return window.APXUI.money(Number(value) || 0); }
  function heading(title, description) {
    return '<header class="page-heading"><span class="eyebrow">APX GROUP · ĐIỀU HÀNH TẬP ĐOÀN</span><h1>' + esc(title) + '</h1><p>' + esc(description) + '</p></header>';
  }
  function api(state) { return window.APXCompanies || null; }
  function companyDefinitions() { return window.APX_DATA.companies || []; }
  function companyCard(company, seed) {
    var branches = company.branches.filter(function (b) { return b.status === "Đang hoạt động"; }).length;
    var staff = company.seedStaff + (api().getCompanyEmployees(company.id).length);
    return '<article class="company-card panel company-live-card" style="--company-color:' + esc(seed.color) + '"><div class="company-card-heading"><span class="company-brand-mark" aria-hidden="true">' + esc(seed.symbol) + '</span><span class="company-heading-copy"><span class="company-sector">' + esc(company.field) + '</span><h2>' + esc(company.name) + '</h2></span><span class="company-growth">' + (company.growth >= 0 ? '+' : '') + Number(company.growth || 0).toFixed(1) + '%</span></div><p class="company-description">' + esc(company.description) + '</p><div class="company-card-stats"><div><small>DOANH THU NGÀY GẦN NHẤT</small><strong>' + fmt(company.revenue) + '</strong></div><div><small>LỢI NHUẬN / NGÀY</small><strong class="' + (company.profit >= 0 ? 'positive' : 'negative') + '">' + fmt(company.profit) + '</strong></div><div><small>TIỀN MẶT CÔNG TY</small><strong>' + fmt(company.cash) + '</strong></div></div><div class="company-card-detail"><span><small>CHI NHÁNH</small><strong>' + branches + '</strong></span><span><small>SẢN PHẨM</small><strong>' + company.products.filter(function (p) { return p.active; }).length + '</strong></span><span><small>NHÂN SỰ</small><strong>' + staff + '</strong></span></div><button class="button button-gold" type="button" data-action="open-company" data-id="' + esc(company.id) + '">Quản lý công ty</button></article>';
  }
  function eventPanel(state) {
    var event = state.pendingBusinessEvent;
    if (!event) return '';
    var company = api().getCompanyById(event.companyId, state);
    return '<section class="panel company-event-panel"><span class="eyebrow">SỰ KIỆN KINH DOANH · NGÀY ' + Number(event.day) + '</span><h2>' + esc(event.title) + '</h2><p>' + esc(event.description) + (company ? ' · ' + esc(company.name) : '') + '</p><div class="company-event-actions">' + event.options.map(function (option) { return '<button class="button ' + (option.id === 'invest' || option.id === 'stock' ? 'button-gold' : '') + '" type="button" data-action="company-event" data-id="' + esc(option.id) + '">' + esc(option.label) + '</button>'; }).join('') + '</div></section>';
  }
  function metric(label, value, note, cls) {
    return '<article class="metric ' + (cls || '') + '"><small>' + esc(label) + '</small><strong>' + esc(value) + '</strong>' + (note ? '<span class="metric-detail">' + esc(note) + '</span>' : '') + '</article>';
  }
  function overviewPage(state) {
    var system = api(state); var summary = system.getCompanySummary(state); var companies = system.getCompanies(state);
    var groupLiquidity = Number(state.treasury) + summary.cash;
    var projectCount = state.projects.length + summary.products;
    var latest = state.ledger[0];
    return heading("APX Group", "Bảng điều hành tập đoàn được tổng hợp từ dòng tiền và hoạt động của từng công ty.") + eventPanel(state) +
      '<section class="group-hero panel"><div class="group-hero-brand"><div class="group-emblem" aria-hidden="true"><span>A</span><i>PX</i></div><span class="group-est">EST. 2021 · VIETNAM</span></div><div class="group-hero-copy"><span class="eyebrow">BÁO CÁO HỢP NHẤT · NGÀY ' + Number(state.day) + '</span><h2>Điều hành ba doanh nghiệp trong cùng hệ sinh thái.</h2><p>Doanh thu hình thành từ sản phẩm, thị trường, chi nhánh, nhân lực và các chiến dịch bạn lựa chọn.</p><div class="group-hero-actions"><button class="button button-gold" type="button" data-action="page" data-page="companies">Quản lý công ty</button><button class="button" type="button" data-action="page" data-page="finance">Báo cáo tài chính</button></div></div></section>' +
      '<section class="group-metrics grid four">' + metric("DOANH THU NGÀY GẦN NHẤT", fmt(summary.revenue), "Tổng từ các công ty", "revenue-stat") + metric("CHI PHÍ NGÀY GẦN NHẤT", fmt(summary.costs), "Lương, sản xuất, thuê và vận hành", "") + metric("LỢI NHUẬN NGÀY GẦN NHẤT", fmt(summary.profit), "Theo sổ từng công ty", "profit-stat") + metric("TIỀN HỢP NHẤT", fmt(groupLiquidity), "Tập đoàn " + fmt(state.treasury) + " · công ty " + fmt(summary.cash), "treasury-stat") + '</section>' +
      '<section class="group-metrics grid four">' + metric("TÀI SẢN HỢP NHẤT", fmt(summary.assets), "Kho, chi nhánh, dự án và tài sản", "") + metric("NỢ CÔNG TY", fmt(summary.debt), "Khoản vay chưa được tập đoàn bù", "") + metric("DÒNG TIỀN HOẠT ĐỘNG", fmt(summary.cashFlow), "Ngày đóng sổ gần nhất", "") + metric("THỊ PHẦN TRUNG BÌNH", Number(summary.marketShare).toFixed(1) + "%", "Trung bình ba lĩnh vực", "") + '</section>' +
      '<section class="group-metrics grid four">' + metric("SỐ CÔNG TY", companies.length, "Đang hoạt động", "") + metric("CHI NHÁNH", summary.branches, "Đang hoạt động", "") + metric("NHÂN SỰ", summary.employees, "Tổng nhân sự công ty", "staff-stat") + metric("SẢN PHẨM / DỰ ÁN", projectCount, "Sản phẩm và dự án đang theo dõi", "") + '</section>' +
      '<section class="company-overview-grid grid two"><article class="panel company-overview-list"><div class="section-title-row"><div><span class="eyebrow">HỆ SINH THÁI APX</span><h2>Kết quả theo công ty</h2></div><button class="button" type="button" data-action="page" data-page="companies">Danh mục</button></div>' + companies.map(function (company) { return '<div class="company-overview-row"><span class="company-mini-mark">' + esc(company.id.slice(0, 1).toUpperCase()) + '</span><span class="company-overview-copy"><strong>' + esc(company.name) + '</strong><small>' + esc(company.field) + '</small></span><span class="company-overview-revenue"><strong>' + fmt(company.profit) + '</strong><small>LỢI NHUẬN · NGÀY</small></span></div>'; }).join('') + '</article><article class="panel company-finance-preview"><div class="section-title-row"><div><span class="eyebrow">ĐÓNG NGÀY GẦN NHẤT</span><h2>Báo cáo hợp nhất</h2></div></div>' + (latest ? '<div class="data-row"><span>Ngày game ' + Number(latest.day) + '</span><strong>' + fmt(latest.profit) + '</strong></div><div class="data-row"><span>Doanh thu</span><strong>' + fmt(latest.revenue) + '</strong></div><div class="data-row"><span>Chi phí</span><strong>' + fmt(latest.cost) + '</strong></div>' : '<p class="character-empty-note">Công ty đang có dự báo vận hành. Báo cáo lịch sử sẽ ghi khi đến ngày game tiếp theo.</p>') + '<button class="button" type="button" data-action="page" data-page="finance">Mở báo cáo tài chính</button></article></section>';
  }
  function companiesPage(state) {
    var system = api(state); var manager = state.companyManager || {}; var company = manager.companyId && system.getCompanyById(manager.companyId, state);
    if (company) return companyManagerPage(company, state);
    var companies = system.getCompanies(state);
    return heading("Công ty thành viên", "Mở hồ sơ riêng để điều hành tài chính, chi nhánh, sản phẩm, nhân sự và marketing.") + eventPanel(state) + '<section class="company-card-grid grid three" aria-label="Công ty APX">' + companies.map(function (item) { var seed = companyDefinitions().find(function (s) { return s.id === item.id; }) || {}; return companyCard(item, seed); }).join('') + '</section><section class="panel company-funding-note"><strong>Ngân quỹ tách biệt</strong><p>Mỗi công ty giữ tiền mặt riêng. Mở trang công ty để điều chuyển vốn giữa APX Group và công ty, mọi khoản chuyển đều ghi vào sổ.</p></section>';
  }
  function tabBar(company, active) {
    return '<nav class="company-manager-tabs" aria-label="Trang quản lý ' + esc(company.name) + '">' + api().getManagerTabs().map(function (tab) { return '<button type="button" class="company-manager-tab ' + (active === tab.id ? 'active' : '') + '" data-action="company-manager-tab" data-tab="' + tab.id + '">' + esc(tab.label) + '</button>'; }).join('') + '</nav>';
  }
  function companyHeader(company, state) {
    var staff = company.seedStaff + api().getCompanyEmployees(company.id, state).length;
    return '<section class="company-manager-header panel"><button type="button" class="button company-back-button" data-action="company-list">← Danh sách công ty</button><div class="company-manager-title"><span class="eyebrow">' + esc(company.field) + ' · THÀNH LẬP ' + esc(company.founded) + '</span><h2>' + esc(company.name) + '</h2><p>' + esc(company.description) + '</p></div><div class="company-manager-header-metrics"><span><small>UY TÍN</small><strong>' + Number(company.reputation).toFixed(1) + '</strong></span><span><small>THỊ PHẦN</small><strong>' + Number(company.marketShare).toFixed(1) + '%</strong></span><span><small>TIỀN</small><strong>' + fmt(company.cash) + '</strong></span><span><small>DOANH THU / NGÀY</small><strong>' + fmt(company.revenue) + '</strong></span><span><small>LỢI NHUẬN / NGÀY</small><strong class="' + (company.profit >= 0 ? 'positive' : 'negative') + '">' + fmt(company.profit) + '</strong></span><span><small>NHÂN SỰ</small><strong>' + staff + '</strong></span></div>' + tabBar(company, state.companyManager.tab || 'overview') + '</section>';
  }
  function breakdownRows(breakdown) {
    breakdown = breakdown || {};
    var items = [['Doanh thu bán hàng', breakdown.revenue], ['Doanh thu dự án', breakdown.projectRevenue], ['Nguyên liệu / sản xuất', breakdown.production], ['Lương', breakdown.payroll], ['Vận hành', breakdown.operations], ['Thuê mặt bằng', breakdown.rent], ['Chi phí dự án', breakdown.projectOperations], ['Lãi vay', breakdown.interest], ['Marketing', breakdown.marketing], ['Nghiên cứu sản phẩm', breakdown.research], ['Chi phí khác', breakdown.other]];
    return items.map(function (item) { return '<div class="data-row"><span>' + esc(item[0]) + '</span><strong>' + fmt(item[1]) + '</strong></div>'; }).join('');
  }
  function historyChart(company) {
    var history = company.history.slice(0, 10).reverse();
    if (!history.length) return '<p class="character-empty-note">Chưa có ngày vận hành được ghi sổ.</p>';
    var max = Math.max(1, history.reduce(function (m, item) { return Math.max(m, Number(item.revenue) || 0); }, 0));
    return '<div class="company-history-chart" role="img" aria-label="Doanh thu theo ngày trong game">' + history.map(function (item) { var height = Math.max(4, Math.round(Number(item.revenue) / max * 100)); return '<span title="Ngày ' + Number(item.day) + ' · doanh thu ' + esc(fmt(item.revenue)) + ' · lợi nhuận ' + esc(fmt(item.profit)) + '"><i style="height:' + height + '%"></i><small>' + Number(item.day) + '</small></span>'; }).join('') + '</div>';
  }
  function managerOverview(company, state) {
    var market = api().getMarkets(state)[company.industryId];
    var activeBranches = company.branches.filter(function (b) { return b.status === 'Đang hoạt động'; });
    return eventPanel(state) + '<section class="company-manager-overview-grid grid two"><article class="panel"><span class="eyebrow">DÒNG TIỀN GẦN NHẤT</span><h3>' + (company.lastDay ? 'Ngày ' + company.lastDay.day : 'Dự báo đến ngày kế tiếp') + '</h3>' + breakdownRows(company.lastDay && company.lastDay.breakdown) + '</article><article class="panel"><span class="eyebrow">THỊ TRƯỜNG LIÊN KẾT</span><h3>' + esc(market ? market.name : company.industryId) + '</h3><div class="data-row"><span>Chỉ số nhu cầu</span><strong>' + (market ? Number(market.index).toFixed(2) : '1.00') + '×</strong></div><div class="data-row"><span>Xu hướng ngày</span><strong>' + (market ? (market.trend >= 0 ? '+' : '') + Number(market.trend).toFixed(2) + '%' : '—') + '</strong></div><div class="data-row"><span>Chi nhánh hoạt động</span><strong>' + activeBranches.length + '</strong></div><div class="data-row"><span>Sản phẩm đang bán</span><strong>' + company.products.filter(function (p) { return p.active; }).length + '</strong></div><p class="character-empty-note">Nhu cầu thay đổi theo thị trường, giá bán, chất lượng, uy tín, nhân lực và quảng cáo.</p></article></section><section class="panel company-history-panel"><div class="section-title-row"><div><span class="eyebrow">LỊCH SỬ DOANH NGHIỆP</span><h2>Doanh thu 10 ngày gần nhất</h2></div><span class="sample-data-label">LƯU TRONG SAVE</span></div>' + historyChart(company) + '</section>';
  }
  function financeTab(company, state) {
    var last = company.lastDay || {}; var flow = last.cashFlow || {};
    var totalAssets = api().getCompanyAssetValue(company, state);
    return '<section class="group-metrics grid four">' + metric('DOANH THU NGÀY', fmt(company.revenue), 'Từ sản phẩm và dự án') + metric('CHI PHÍ NGÀY', fmt(company.costs), 'Theo từng khoản thực tế') + metric('LỢI NHUẬN NGÀY', fmt(company.profit), 'Doanh thu − chi phí', company.profit >= 0 ? 'profit-stat' : '') + metric('TÀI SẢN / VỐN', fmt(totalAssets) + ' / ' + fmt(company.capital), 'Tài sản ghi nhận · vốn kế toán', '') + '</section><section class="company-manager-overview-grid grid two"><article class="panel"><span class="eyebrow">BÁO CÁO LÃI LỖ</span><h2>Ngày ' + Number(last.day || state.day) + '</h2>' + breakdownRows(last.breakdown) + '<div class="data-row"><span>Lợi nhuận sau chi phí</span><strong class="' + (company.profit >= 0 ? 'positive' : 'negative') + '">' + fmt(company.profit) + '</strong></div></article><article class="panel"><span class="eyebrow">BÁO CÁO DÒNG TIỀN</span><h2>Tiền mặt công ty</h2><div class="data-row"><span>Tiền đầu kỳ</span><strong>' + fmt(flow.opening) + '</strong></div><div class="data-row"><span>Tiền vào từ hoạt động</span><strong>' + fmt(flow.inflow) + '</strong></div><div class="data-row"><span>Tiền chi vận hành</span><strong>' + fmt(flow.outflow) + '</strong></div><div class="data-row"><span>Chuyển về APX Group</span><strong>' + fmt(flow.transferredToGroup) + '</strong></div><div class="data-row"><span>Tập đoàn hỗ trợ</span><strong>' + fmt(flow.groupSupport) + '</strong></div><div class="data-row"><span>Nợ phát sinh trong ngày</span><strong>' + fmt(flow.debtBorrowing) + '</strong></div><div class="data-row"><span>Trả nợ</span><strong>' + fmt(flow.debtRepayment) + '</strong></div><div class="data-row"><span>Tiền cuối kỳ hiện tại</span><strong>' + fmt(company.cash) + '</strong></div></article></section><section class="panel company-history-panel"><span class="eyebrow">LỊCH SỬ LỢI NHUẬN</span><h2>Doanh thu theo ngày</h2>' + historyChart(company) + '<div class="company-ledger-list">' + company.history.slice(0, 12).map(function (row) { return '<div class="data-row"><span>Ngày ' + Number(row.day) + ' · doanh thu ' + fmt(row.revenue) + ' · chi phí ' + fmt(row.costs) + '</span><strong class="' + (row.profit >= 0 ? 'positive' : 'negative') + '">' + fmt(row.profit) + '</strong></div>'; }).join('') + '</div></section>';
  }
  function branchTab(company, state) {
    var branches = company.branches;
    var employees = api().getCompanyEmployees(company.id, state);
    return '<section class="company-branch-grid grid two">' + branches.map(function (branch) {
      var assigned = employees.filter(function (person) { return person.branchId === branch.id; });
      var headcount = (branch.seedEmployees || 0) + assigned.length;
      return '<article class="panel company-branch-card ' + (branch.status !== 'Đang hoạt động' ? 'is-closed' : '') + '"><div class="company-branch-heading"><span class="company-mini-mark">' + esc(branch.type.slice(0, 1)) + '</span><span><small>' + esc(branch.type) + ' · CẤP ' + Number(branch.level) + '</small><h3>' + esc(branch.name) + '</h3></span><strong>' + esc(branch.status) + '</strong></div><div class="data-row"><span>Vị trí</span><strong>' + esc(branch.location) + '</strong></div><div class="data-row"><span>Nhân viên</span><strong>' + headcount + ' / ' + Math.round(branch.capacity / 12) + '</strong></div><div class="data-row"><span>Doanh thu gần nhất</span><strong>' + fmt(branch.revenue) + '</strong></div><div class="data-row"><span>Chi phí gần nhất</span><strong>' + fmt(branch.costs) + '</strong></div><div class="data-row"><span>Hiệu suất</span><strong>' + Math.round(branch.efficiency * 100) + '%</strong></div>' + (branch.status === 'Đang hoạt động' ? '<div class="company-branch-actions"><button class="button" type="button" data-action="company-upgrade-branch" data-id="' + esc(branch.id) + '" data-company="' + esc(company.id) + '">Nâng cấp · ' + fmt(180000000 * branch.level) + '</button>' + (!branch.isInitial ? '<button class="button" type="button" data-action="company-close-branch" data-id="' + esc(branch.id) + '" data-company="' + esc(company.id) + '">Đóng chi nhánh</button>' : '') + '</div>' : '') + '</article>';
    }).join('') + '</section><section class="panel company-form-panel"><span class="eyebrow">MỞ RỘNG MẠNG LƯỚI</span><h2>Mở chi nhánh mới</h2><p>Chi phí được trừ từ tiền mặt của ' + esc(company.name) + '.</p><form id="companyOpenBranchForm" class="company-inline-form"><input type="hidden" name="companyId" value="' + esc(company.id) + '"><label>Tên chi nhánh<input name="name" minlength="3" maxlength="40" placeholder="Ví dụ: APX Coffee Bình Thạnh mới" required></label><label>Vị trí<input name="location" minlength="2" maxlength="40" placeholder="Quận / khu vực" required></label><button class="button button-gold" type="submit">Mở chi nhánh · ' + fmt(company.id === 'coffee' ? 720000000 : company.id === 'tech' ? 1150000000 : 980000000) + '</button></form></section>';
  }
  function productTab(company) {
    var products = company.products;
    return '<section class="company-product-grid grid two">' + products.map(function (product) {
      return '<article class="panel company-product-card ' + (!product.active ? 'is-inactive' : '') + '"><div class="company-product-top"><span class="eyebrow">' + (product.active ? 'ĐANG BÁN' : 'TẠM DỪNG') + '</span><strong>CHẤT LƯỢNG ' + Number(product.quality) + '</strong></div><h3>' + esc(product.name) + '</h3><div class="data-row"><span>Giá bán hiện tại</span><strong>' + fmt(product.price) + '</strong></div><div class="data-row"><span>Chi phí / đơn vị</span><strong>' + fmt(product.unitCost) + '</strong></div><div class="data-row"><span>Lượt bán ngày gần nhất</span><strong>' + Number(product.unitsSold || 0).toFixed(1) + '</strong></div><div class="data-row"><span>Doanh thu gần nhất</span><strong>' + fmt(product.revenue) + '</strong></div><form class="company-price-form" data-company-form="product-price"><input type="hidden" name="companyId" value="' + esc(company.id) + '"><input type="hidden" name="productId" value="' + esc(product.id) + '"><label>Giá mới<input name="price" type="number" min="' + Math.round(product.basePrice * .5) + '" max="' + Math.round(product.basePrice * 2) + '" step="1000" value="' + Number(product.price) + '" required></label><button class="button" type="submit">Cập nhật giá</button></form><div class="company-product-actions"><button class="button" type="button" data-action="company-toggle-product" data-company="' + esc(company.id) + '" data-id="' + esc(product.id) + '">' + (product.active ? 'Tạm dừng bán' : 'Bật bán lại') + '</button><button class="button" type="button" data-action="company-upgrade-product" data-company="' + esc(company.id) + '" data-id="' + esc(product.id) + '">Nâng chất lượng</button></div></article>';
    }).join('') + '</section><section class="panel company-form-panel"><span class="eyebrow">NGHIÊN CỨU VÀ PHÁT TRIỂN</span><h2>Đưa sản phẩm mới ra thị trường</h2><form id="companyCreateProductForm" class="company-inline-form"><input type="hidden" name="companyId" value="' + esc(company.id) + '"><label>Tên sản phẩm<input name="name" minlength="3" maxlength="45" placeholder="Tên dịch vụ hoặc sản phẩm" required></label><label>Giá bán<input name="price" type="number" min="1000" step="1000" placeholder="500000" required></label><button class="button button-gold" type="submit">Phát triển sản phẩm</button></form></section>';
  }
  function staffTab(company, state) {
    var system = api(state); var hires = Object.keys(state.companyAssignments || {}).map(function (id) { var person = (window.APX_DATA.candidates || []).find(function (item) { return item.id === id; }); return person && state.companyAssignments[id] ? Object.assign({}, person, state.companyAssignments[id]) : null; }).filter(Boolean);
    var options = system.getCompanies(state).map(function (item) { return item.branches.filter(function (branch) { return branch.status === 'Đang hoạt động'; }).map(function (branch) { return '<option value="' + esc(item.id + '|' + branch.id) + '">' + esc(item.name + ' · ' + branch.name) + '</option>'; }).join(''); }).join('');
    return '<section class="panel company-staff-intro"><span class="eyebrow">KẾT NỐI MODULE NHÂN VIÊN</span><h2>' + esc(company.name) + '</h2><p>Nhân viên mới được ghi vào hồ sơ phân công. Lương và hiệu suất tác động tới chi phí, năng lực vận hành.</p><div class="data-row"><span>Nhân viên nền tảng</span><strong>' + company.seedStaff + '</strong></div><div class="data-row"><span>Đã tuyển thêm</span><strong>' + hires.length + '</strong></div><a class="button" href="#" data-action="navigate" data-section="employees">Mở danh sách nhân viên</a></section>' + (hires.length ? '<section class="company-staff-grid grid two">' + hires.map(function (person) { var assignment = state.companyAssignments[person.id]; var assignedCompany = system.getCompanyById(assignment.companyId, state); var branch = assignedCompany && assignedCompany.branches.find(function (item) { return item.id === assignment.branchId; }); var selected = assignment.companyId + '|' + assignment.branchId; return '<article class="panel company-staff-card"><div class="section-title-row"><div><h3>' + esc(person.name) + '</h3><small>' + esc(assignment.role) + ' · ' + esc(assignment.department) + '</small></div><strong>' + Number(assignment.performance) + ' / 100</strong></div><div class="data-row"><span>Đang làm tại</span><strong>' + esc(assignedCompany ? assignedCompany.name : '') + ' · ' + esc(branch ? branch.name : '') + '</strong></div><div class="data-row"><span>Lương tháng</span><strong>' + fmt(assignment.salary) + '</strong></div><div class="company-staff-actions"><button class="button" type="button" data-action="company-adjust-salary" data-id="' + esc(person.id) + '" data-delta="-1000000">− ₫1 triệu</button><button class="button" type="button" data-action="company-adjust-salary" data-id="' + esc(person.id) + '" data-delta="1000000">+ ₫1 triệu</button></div><label class="company-move-select">Điều chuyển<select data-change="move-company-employee" data-id="' + esc(person.id) + '">' + options.replace('value="' + esc(selected) + '"', 'value="' + esc(selected) + '" selected') + '</select></label></article>'; }).join('') + '</section>' : '<p class="panel character-empty-note">Chưa tuyển thêm nhân viên cho tập đoàn. Ứng viên tuyển mới sẽ được phân vào công ty phù hợp với chuyên môn.</p>');
  }
  function marketingTab(company) {
    var campaigns = api().getCampaignDefinitions();
    return '<section class="company-campaign-grid grid three">' + campaigns.map(function (campaign) { return '<article class="panel company-campaign-card"><span class="eyebrow">CHIẾN DỊCH · ' + campaign.days + ' NGÀY</span><h3>' + esc(campaign.name) + '</h3><p>' + esc(campaign.description) + '</p><div class="data-row"><span>Chi phí</span><strong>' + fmt(campaign.cost) + '</strong></div><div class="data-row"><span>Tác động nhu cầu</span><strong>+' + Math.round(campaign.demandBoost * 100) + '%</strong></div><button class="button button-gold" type="button" data-action="company-run-marketing" data-company="' + esc(company.id) + '" data-id="' + esc(campaign.id) + '">Chạy chiến dịch</button></article>'; }).join('') + '</section><section class="panel company-active-campaigns"><span class="eyebrow">ĐANG TRIỂN KHAI</span><h2>Chiến dịch của ' + esc(company.name) + '</h2>' + (company.campaigns.length ? company.campaigns.map(function (campaign) { return '<div class="data-row"><span>' + esc(campaign.name) + '</span><strong>Còn ' + Number(campaign.daysLeft) + ' ngày · +' + Math.round(campaign.demandBoost * 100) + '% nhu cầu</strong></div>'; }).join('') : '<p class="character-empty-note">Chưa có chiến dịch đang hoạt động.</p>') + '</section>';
  }
  function operationsTab(company, state) {
    return '<section class="company-operations-grid grid two"><article class="panel"><span class="eyebrow">KHO NGUYÊN LIỆU</span><h2>' + esc(company.inventory.name) + '</h2><div class="data-row"><span>Tồn kho</span><strong>' + Number(company.inventory.stock).toFixed(0) + ' đơn vị</strong></div><div class="data-row"><span>Giá nhập / đơn vị</span><strong>' + fmt(company.inventory.unitCost) + '</strong></div><div class="data-row"><span>Giá trị tồn ước tính</span><strong>' + fmt(company.inventory.value) + '</strong></div><form id="companyInventoryForm" class="company-inline-form"><input type="hidden" name="companyId" value="' + esc(company.id) + '"><label>Số lượng nhập<input name="quantity" type="number" min="1" max="10000" step="100" value="500" required></label><button class="button button-gold" type="submit">Nhập kho bằng tiền công ty</button></form></article><article class="panel"><span class="eyebrow">DÒNG TIỀN NỘI BỘ</span><h2>Điều chuyển vốn</h2><p>Tiền cá nhân không bị trừ ở đây. Các giao dịch được ghi vào sổ điều chuyển tập đoàn.</p><form id="companyTransferForm" class="company-transfer-form"><input type="hidden" name="companyId" value="' + esc(company.id) + '"><label>Số tiền<input name="amount" type="number" min="1000000" step="1000000" value="50000000" required></label><label>Hướng chuyển<select name="direction"><option value="to-company">APX Group → công ty</option><option value="to-group">Công ty → APX Group</option></select></label><button class="button button-gold" type="submit">Ghi nhận điều chuyển</button></form><div class="data-row"><span>Tiền mặt tập đoàn</span><strong>' + fmt(state.treasury) + '</strong></div><div class="data-row"><span>Tiền mặt ' + esc(company.name) + '</span><strong>' + fmt(company.cash) + '</strong></div></article></section><section class="panel company-ledger-panel"><span class="eyebrow">GIAO DỊCH CÔNG TY</span><h2>Sổ điều chuyển và đầu tư</h2>' + (state.companyFinanceLedger.filter(function (row) { return row.companyId === company.id; }).slice(0, 12).map(function (row) { return '<div class="data-row"><span>Ngày ' + Number(row.day) + ' · ' + esc(row.note) + '</span><strong>' + fmt(row.amount) + '</strong></div>'; }).join('') || '<p class="character-empty-note">Chưa có giao dịch ghi nhận.</p>') + '</section>';
  }
  function expansionTab(company) {
    var marketListings = (window.APX_DATA.buildings || []).filter(function (building) { return !building.owned && building.status === 'Mở bán' && !window.APXGame.state.buildings.includes(building.id) && !(window.APXGame.state.companyBuildingOwnership || {})[building.id]; });
    return '<section class="panel company-expansion-intro"><span class="eyebrow">TÁI ĐẦU TƯ CÓ KIỂM SOÁT</span><h2>Vốn và tài sản của ' + esc(company.name) + '</h2><p>Mọi quyết định mở rộng chỉ dùng tiền mặt của công ty. Tập đoàn có thể cấp vốn qua trang Kho / Vận hành.</p><div class="data-row"><span>Vốn kế toán</span><strong>' + fmt(company.capital) + '</strong></div><div class="data-row"><span>Tiền mặt</span><strong>' + fmt(company.cash) + '</strong></div><div class="data-row"><span>Tài sản ghi sổ</span><strong>' + fmt(company.assets.reduce(function (sum, a) { return sum + (Number(a.value) || 0); }, 0)) + '</strong></div></section><section class="company-expansion-list grid two">' + marketListings.map(function (building) { return '<article class="panel"><span class="eyebrow">' + esc(building.type) + ' · ' + esc(building.district) + '</span><h3>' + esc(building.name) + '</h3><p>' + esc(building.detail) + '</p><div class="data-row"><span>Giá mua</span><strong>' + fmt(building.value) + '</strong></div><button class="button button-gold" type="button" data-action="company-buy-asset" data-company="' + esc(company.id) + '" data-id="' + esc(building.id) + '">Mua bằng tiền công ty</button></article>'; }).join('') + '</section><section class="panel"><span class="eyebrow">TÀI SẢN ĐANG SỞ HỮU</span><h2>Tài sản công ty</h2>' + (company.assets.length ? company.assets.map(function (asset) { return '<div class="data-row"><span>' + esc(asset.name) + ' · ' + esc(asset.kind) + '</span><strong>' + fmt(asset.value) + '</strong></div>'; }).join('') : '<p class="character-empty-note">Chưa có tài sản ghi nhận.</p>') + '</section>';
  }
  function companyManagerPage(company, state) {
    var tab = api().getManagerTabs().some(function (item) { return item.id === state.companyManager.tab; }) ? state.companyManager.tab : 'overview';
    var content = tab === 'finance' ? financeTab(company, state) : tab === 'branches' ? branchTab(company, state) : tab === 'products' ? productTab(company) : tab === 'staff' ? staffTab(company, state) : tab === 'marketing' ? marketingTab(company) : tab === 'operations' ? operationsTab(company, state) : tab === 'expansion' ? expansionTab(company) : managerOverview(company, state);
    return heading(company.name, "Doanh nghiệp của bạn · Kết quả mỗi ngày phụ thuộc vào các quyết định vận hành.") + companyHeader(company, state) + '<div class="company-manager-content">' + content + '</div>';
  }
  function financePage(state) {
    var system = api(state); var summary = system.getCompanySummary(state); var ledger = state.ledger || [];
    return heading("Tài chính tập đoàn", "Báo cáo hợp nhất từ sổ riêng của từng công ty, dự án và dòng tiền nội bộ.") + '<section class="group-metrics grid four">' + metric('NGÂN QUỸ APX GROUP', fmt(state.treasury), 'Quỹ trung tâm, tách biệt tiền công ty') + metric('TIỀN MẶT CÁC CÔNG TY', fmt(summary.cash), 'Số dư từng pháp nhân') + metric('NỢ CÔNG TY', fmt(summary.debt), 'Thiếu hụt chưa được tập đoàn bù') + metric('DÒNG TIỀN HOẠT ĐỘNG', fmt(summary.cashFlow), 'Ngày đóng sổ gần nhất') + '</section><section class="group-metrics grid four">' + metric('DOANH THU GẦN NHẤT', fmt(summary.revenue), 'Tổng hoạt động công ty') + metric('CHI PHÍ GẦN NHẤT', fmt(summary.costs), 'Sổ lãi lỗ ngày gần nhất') + metric('LỢI NHUẬN GẦN NHẤT', fmt(summary.profit), 'Sau chi phí từng đơn vị') + metric('TÀI SẢN HỢP NHẤT', fmt(summary.assets), 'Kho, chi nhánh và dự án') + metric('TÀI SẢN HỢP NHẤT', fmt(summary.assets), 'Kho, chi nhánh và dự án') + '</section><section class="panel company-finance-preview"><span class="eyebrow">BÁO CÁO THEO CÔNG TY</span><h2>Ngày vận hành hiện tại</h2>' + summary.companies.map(function (company) { return '<div class="data-row"><span>' + esc(company.name) + ' · doanh thu ' + fmt(company.revenue) + ' · chi phí ' + fmt(company.costs) + '</span><strong class="' + (company.profit >= 0 ? 'positive' : 'negative') + '">' + fmt(company.profit) + '</strong></div>'; }).join('') + '</section><section class="panel finance-ledger-panel"><span class="eyebrow">SỔ TÀI CHÍNH TẬP ĐOÀN</span><h2>Ngày đóng sổ gần nhất</h2>' + (ledger.length ? ledger.slice(0, 20).map(function (row) { return '<article class="company-day-ledger"><div class="data-row"><span>Ngày ' + Number(row.day) + ' · doanh thu ' + fmt(row.revenue) + ' · chi phí ' + fmt(row.cost) + '</span><strong>' + fmt(row.profit) + '</strong></div>' + ((row.companies || []).map(function (item) { return '<div class="data-row company-day-ledger-detail"><span>' + esc(item.name) + (item.transferred ? ' · chuyển tập đoàn ' + fmt(item.transferred) : '') + '</span><strong>' + fmt(item.profit) + '</strong></div>'; }).join('')) + '</article>'; }).join('') : '<p class="character-empty-note">Các công ty đang có dự báo ban đầu. Lịch sử sẽ được ghi tự động khi ngày game chuyển.</p>') + '</section><section class="panel"><span class="eyebrow">GIAO DỊCH VỐN NỘI BỘ</span><h2>Chuyển giữa tập đoàn và công ty</h2>' + (state.companyFinanceLedger || []).slice(0, 20).map(function (row) { var company = system.getCompanyById(row.companyId, state); return '<div class="data-row"><span>Ngày ' + Number(row.day) + ' · ' + esc(company ? company.name : 'APX Group') + ' · ' + esc(row.note) + '</span><strong>' + fmt(row.amount) + '</strong></div>'; }).join('') + '</section>';
  }
  function marketPage(state) {
    var markets = api(state).getMarkets(state); var competitors = api(state).getCompetitors(state);
    return heading("Thị trường", "Chỉ số ngành và đối thủ biến động theo ngày, tác động đến nhu cầu các công ty APX.") + '<section class="market-sector-grid grid three">' + Object.keys(markets).map(function (id, index) { var market = markets[id]; return '<article class="market-sector-card panel"><div class="market-sector-top"><span class="market-sector-index">0' + (index + 1) + '</span><span class="market-outlook">' + esc(market.outlook) + '</span></div><span class="eyebrow">CHỈ SỐ NGÀNH</span><h3>' + esc(market.name) + '</h3><p>' + Number(market.index).toFixed(2) + '× nhu cầu · xu hướng ' + (market.trend >= 0 ? '+' : '') + Number(market.trend).toFixed(2) + '%/ngày</p>' + historyChart({ history: market.history.map(function (point) { return { day: point.day, revenue: point.index * 100 }; }) }) + '</article>'; }).join('') + '</section><section class="market-competitors-section"><div class="section-title-row"><div><span class="eyebrow">DOANH NGHIỆP THAM CHIẾU</span><h2>Đối thủ mô phỏng</h2></div><span class="sample-data-label">CẬP NHẬT MỖI NGÀY</span></div><div class="market-competitor-grid grid three">' + competitors.map(function (competitor) { return '<article class="market-competitor panel"><span class="competitor-symbol" aria-hidden="true">' + esc(competitor.name.slice(0, 1)) + '</span><span class="eyebrow">' + esc((markets[competitor.sector] || {}).name || competitor.sector) + '</span><h3>' + esc(competitor.name) + '</h3><p>Chiến lược: ' + esc(competitor.strategy) + '</p><div class="data-row"><span>Sức mạnh</span><strong>' + Number(competitor.strength) + ' / 100</strong></div><div class="data-row"><span>Thị phần</span><strong>' + Number(competitor.marketShare).toFixed(1) + '%</strong></div><div class="data-row"><span>Chỉ số giá</span><strong>' + Number(competitor.priceIndex).toFixed(2) + '×</strong></div></article>'; }).join('') + '</div></section><section class="panel"><span class="eyebrow">SỰ KIỆN GẦN ĐÂY</span><h2>Quyết định kinh doanh</h2>' + (state.companyEventHistory || []).slice(0, 10).map(function (item) { var company = api().getCompanyById(item.companyId, state); return '<div class="data-row"><span>Ngày ' + Number(item.day) + ' · ' + esc(company ? company.name : '') + ' · ' + esc(item.title) + ' · ' + esc(item.choice) + '</span><strong>' + esc(item.result) + '</strong></div>'; }).join('') + '</section>' + eventPanel(state);
  }
  window.APXPages.company = function (page, state) {
    if (!api()) return heading("APX Group", "Đang tải dữ liệu công ty.");
    if (page === 'companies') return companiesPage(state);
    if (page === 'finance') return financePage(state);
    if (page === 'market') return marketPage(state);
    return overviewPage(state);
  };
})();
